onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /TestBench/pos_l3_vif/clk_156m25
add wave -noupdate /TestBench/pos_l3_vif/pkt_rx_avail
add wave -noupdate /TestBench/pos_l3_vif/pkt_rx_data
add wave -noupdate /TestBench/pos_l3_vif/pkt_rx_eop
add wave -noupdate /TestBench/pos_l3_vif/pkt_rx_err
add wave -noupdate /TestBench/pos_l3_vif/pkt_rx_mod
add wave -noupdate /TestBench/pos_l3_vif/pkt_rx_ren
add wave -noupdate /TestBench/pos_l3_vif/pkt_rx_sop
add wave -noupdate /TestBench/pos_l3_vif/pkt_rx_val
add wave -noupdate /TestBench/pos_l3_vif/pkt_tx_data
add wave -noupdate /TestBench/pos_l3_vif/pkt_tx_eop
add wave -noupdate /TestBench/pos_l3_vif/pkt_tx_full
add wave -noupdate /TestBench/pos_l3_vif/pkt_tx_mod
add wave -noupdate /TestBench/pos_l3_vif/pkt_tx_sop
add wave -noupdate /TestBench/pos_l3_vif/pkt_tx_val
add wave -noupdate /TestBench/pos_l3_vif/reset_156m25_n
add wave -noupdate /TestBench/pos_l3_vif/rxdfifo_ren
add wave -noupdate /TestBench/pos_l3_vif/status_rxdfifo_udflow_tog
add wave -noupdate /TestBench/pos_l3_vif/txdfifo_walmost_full
add wave -noupdate /TestBench/pos_l3_vif/txdfifo_wfull
add wave -noupdate /TestBench/dut/tx_eq0/clk_156m25
add wave -noupdate /TestBench/dut/tx_eq0/next_txd_ovflow
add wave -noupdate /TestBench/dut/tx_eq0/pkt_tx_data
add wave -noupdate /TestBench/dut/tx_eq0/pkt_tx_eop
add wave -noupdate /TestBench/dut/tx_eq0/pkt_tx_full
add wave -noupdate /TestBench/dut/tx_eq0/pkt_tx_mod
add wave -noupdate /TestBench/dut/tx_eq0/pkt_tx_sop
add wave -noupdate /TestBench/dut/tx_eq0/pkt_tx_val
add wave -noupdate /TestBench/dut/tx_eq0/reset_156m25_n
add wave -noupdate /TestBench/dut/tx_eq0/status_txdfifo_ovflow_tog
add wave -noupdate /TestBench/dut/tx_eq0/txd_ovflow
add wave -noupdate /TestBench/dut/tx_eq0/txdfifo_walmost_full
add wave -noupdate /TestBench/dut/tx_eq0/txdfifo_wdata
add wave -noupdate /TestBench/dut/tx_eq0/txdfifo_wen
add wave -noupdate /TestBench/dut/tx_eq0/txdfifo_wfull
add wave -noupdate /TestBench/dut/tx_eq0/txdfifo_wstatus
add wave -noupdate /TestBench/dut/tx_data_fifo0/clk_xgmii_tx
add wave -noupdate /TestBench/dut/tx_data_fifo0/clk_156m25
add wave -noupdate /TestBench/dut/tx_data_fifo0/reset_xgmii_tx_n
add wave -noupdate /TestBench/dut/tx_data_fifo0/reset_156m25_n
add wave -noupdate /TestBench/dut/tx_data_fifo0/txdfifo_wdata
add wave -noupdate /TestBench/dut/tx_data_fifo0/txdfifo_wstatus
add wave -noupdate /TestBench/dut/tx_data_fifo0/txdfifo_wen
add wave -noupdate /TestBench/dut/tx_data_fifo0/txdfifo_ren
add wave -noupdate /TestBench/dut/tx_data_fifo0/txdfifo_wfull
add wave -noupdate /TestBench/dut/tx_data_fifo0/txdfifo_walmost_full
add wave -noupdate /TestBench/dut/tx_data_fifo0/txdfifo_rdata
add wave -noupdate /TestBench/dut/tx_data_fifo0/txdfifo_rstatus
add wave -noupdate /TestBench/dut/tx_data_fifo0/txdfifo_rempty
add wave -noupdate /TestBench/dut/tx_data_fifo0/txdfifo_ralmost_empty
add wave -noupdate /TestBench/dut/tx_dq0/clk_xgmii_tx
add wave -noupdate /TestBench/dut/tx_dq0/reset_xgmii_tx_n
add wave -noupdate /TestBench/dut/tx_dq0/ctrl_tx_enable_ctx
add wave -noupdate /TestBench/dut/tx_dq0/status_local_fault_ctx
add wave -noupdate /TestBench/dut/tx_dq0/status_remote_fault_ctx
add wave -noupdate /TestBench/dut/tx_dq0/txdfifo_rdata
add wave -noupdate /TestBench/dut/tx_dq0/txdfifo_rstatus
add wave -noupdate /TestBench/dut/tx_dq0/txdfifo_rempty
add wave -noupdate /TestBench/dut/tx_dq0/txdfifo_ralmost_empty
add wave -noupdate /TestBench/dut/tx_dq0/txhfifo_rdata
add wave -noupdate /TestBench/dut/tx_dq0/txhfifo_rstatus
add wave -noupdate /TestBench/dut/tx_dq0/txhfifo_rempty
add wave -noupdate /TestBench/dut/tx_dq0/txhfifo_ralmost_empty
add wave -noupdate /TestBench/dut/tx_dq0/txhfifo_wfull
add wave -noupdate /TestBench/dut/tx_dq0/txhfifo_walmost_full
add wave -noupdate /TestBench/dut/tx_dq0/txdfifo_ren
add wave -noupdate /TestBench/dut/tx_dq0/txhfifo_ren
add wave -noupdate /TestBench/dut/tx_dq0/txhfifo_wdata
add wave -noupdate /TestBench/dut/tx_dq0/txhfifo_wstatus
add wave -noupdate /TestBench/dut/tx_dq0/txhfifo_wen
add wave -noupdate /TestBench/dut/tx_dq0/xgmii_txd
add wave -noupdate /TestBench/dut/tx_dq0/xgmii_txc
add wave -noupdate /TestBench/dut/tx_dq0/status_txdfifo_udflow_tog
add wave -noupdate /TestBench/dut/tx_dq0/xgxs_txd
add wave -noupdate /TestBench/dut/tx_dq0/xgxs_txc
add wave -noupdate /TestBench/dut/tx_dq0/next_xgxs_txd
add wave -noupdate /TestBench/dut/tx_dq0/next_xgxs_txc
add wave -noupdate /TestBench/dut/tx_dq0/curr_state
add wave -noupdate /TestBench/dut/tx_dq0/next_state
add wave -noupdate /TestBench/dut/tx_dq0/curr_state_rd
add wave -noupdate /TestBench/dut/tx_dq0/next_state_rd
add wave -noupdate /TestBench/dut/tx_dq0/start_on_lane0
add wave -noupdate /TestBench/dut/tx_dq0/next_start_on_lane0
add wave -noupdate /TestBench/dut/tx_dq0/ifg_deficit
add wave -noupdate /TestBench/dut/tx_dq0/next_ifg_deficit
add wave -noupdate /TestBench/dut/tx_dq0/ifg_4b_add
add wave -noupdate /TestBench/dut/tx_dq0/next_ifg_4b_add
add wave -noupdate /TestBench/dut/tx_dq0/ifg_8b_add
add wave -noupdate /TestBench/dut/tx_dq0/next_ifg_8b_add
add wave -noupdate /TestBench/dut/tx_dq0/ifg_8b2_add
add wave -noupdate /TestBench/dut/tx_dq0/next_ifg_8b2_add
add wave -noupdate /TestBench/dut/tx_dq0/eop
add wave -noupdate /TestBench/dut/tx_dq0/next_eop
add wave -noupdate /TestBench/dut/tx_dq0/xgxs_txd_barrel
add wave -noupdate /TestBench/dut/tx_dq0/xgxs_txc_barrel
add wave -noupdate /TestBench/dut/tx_dq0/txhfifo_rdata_d1
add wave -noupdate /TestBench/dut/tx_dq0/byte_cnt
add wave -noupdate /TestBench/dut/tx_dq0/crc32_d64
add wave -noupdate /TestBench/dut/tx_dq0/crc32_d8
add wave -noupdate /TestBench/dut/tx_dq0/crc32_tx
add wave -noupdate /TestBench/dut/tx_dq0/shift_crc_data
add wave -noupdate /TestBench/dut/tx_dq0/shift_crc_eop
add wave -noupdate /TestBench/dut/tx_dq0/shift_crc_cnt
add wave -noupdate /TestBench/dut/tx_dq0/crc_data
add wave -noupdate /TestBench/dut/tx_dq0/frame_available
add wave -noupdate /TestBench/dut/tx_dq0/next_frame_available
add wave -noupdate /TestBench/dut/tx_dq0/next_txhfifo_wdata
add wave -noupdate /TestBench/dut/tx_dq0/next_txhfifo_wstatus
add wave -noupdate /TestBench/dut/tx_dq0/next_txhfifo_wen
add wave -noupdate /TestBench/dut/tx_dq0/txdfifo_ren_d1
add wave -noupdate /TestBench/dut/tx_hold_fifo0/clk_xgmii_tx
add wave -noupdate /TestBench/dut/tx_hold_fifo0/reset_xgmii_tx_n
add wave -noupdate /TestBench/dut/tx_hold_fifo0/txhfifo_wdata
add wave -noupdate /TestBench/dut/tx_hold_fifo0/txhfifo_wstatus
add wave -noupdate /TestBench/dut/tx_hold_fifo0/txhfifo_wen
add wave -noupdate /TestBench/dut/tx_hold_fifo0/txhfifo_ren
add wave -noupdate /TestBench/dut/tx_hold_fifo0/txhfifo_wfull
add wave -noupdate /TestBench/dut/tx_hold_fifo0/txhfifo_walmost_full
add wave -noupdate /TestBench/dut/tx_hold_fifo0/txhfifo_rdata
add wave -noupdate /TestBench/dut/tx_hold_fifo0/txhfifo_rstatus
add wave -noupdate /TestBench/dut/tx_hold_fifo0/txhfifo_rempty
add wave -noupdate /TestBench/dut/tx_hold_fifo0/txhfifo_ralmost_empty
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {257539 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 456
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {253030 ps} {278970 ps}
